import type { CompanyType } from "@/generated/prisma/enums";

export const APP_NAME = "Job Search";

export const SKILL_ALIASES: Record<string, string> = {
  node: "Node.js",
  nodejs: "Node.js",
  "node.js": "Node.js",
  react: "React",
  reactjs: "React",
  "react.js": "React",
  nextjs: "Next.js",
  "next.js": "Next.js",
  ts: "TypeScript",
  typescript: "TypeScript",
  js: "JavaScript",
  javascript: "JavaScript",
  py: "Python",
  python: "Python",
  java: "Java",
  golang: "Go",
  go: "Go",
  rust: "Rust",
  postgres: "PostgreSQL",
  postgresql: "PostgreSQL",
  psql: "PostgreSQL",
  k8s: "Kubernetes",
  kubernetes: "Kubernetes",
  docker: "Docker",
  aws: "AWS",
  "amazon web services": "AWS",
  gcp: "GCP",
  "google cloud": "GCP",
  azure: "Azure",
  spring: "Spring Boot",
  "spring boot": "Spring Boot",
  springboot: "Spring Boot",
  kafka: "Kafka",
  redis: "Redis",
  graphql: "GraphQL",
  rest: "REST",
  "rest api": "REST",
  sql: "SQL",
  mongodb: "MongoDB",
  mongo: "MongoDB",
  terraform: "Terraform",
  ci: "CI/CD",
  "ci/cd": "CI/CD",
  cicd: "CI/CD",
  git: "Git",
  github: "GitHub",
  gitlab: "GitLab",
  tailwind: "Tailwind CSS",
  "tailwind css": "Tailwind CSS",
  tailwindcss: "Tailwind CSS",
  express: "Express",
  expressjs: "Express",
  "express.js": "Express",
  django: "Django",
  flask: "Flask",
  rails: "Ruby on Rails",
  "ruby on rails": "Ruby on Rails",
  kotlin: "Kotlin",
  swift: "Swift",
  scala: "Scala",
  cplusplus: "C++",
  "c++": "C++",
  csharp: "C#",
  "c#": "C#",
  dotnet: ".NET",
  ".net": ".NET",

  // --- ML / Data Science / AI ---
  ml: "Machine Learning",
  "machine learning": "Machine Learning",
  dl: "Deep Learning",
  "deep learning": "Deep Learning",
  ai: "Artificial Intelligence",
  "artificial intelligence": "Artificial Intelligence",
  "data science": "Data Science",
  datascience: "Data Science",
  "data scientist": "Data Science",
  "data engineering": "Data Engineering",
  dataengineering: "Data Engineering",
  nlp: "NLP",
  "natural language processing": "NLP",
  "computer vision": "Computer Vision",
  "reinforcement learning": "Reinforcement Learning",
  rl: "Reinforcement Learning",
  "neural network": "Neural Networks",
  "neural networks": "Neural Networks",
  tensorflow: "TensorFlow",
  tf: "TensorFlow",
  pytorch: "PyTorch",
  torch: "PyTorch",
  keras: "Keras",
  "scikit-learn": "Scikit-Learn",
  sklearn: "Scikit-Learn",
  pandas: "Pandas",
  numpy: "NumPy",
  matplotlib: "Matplotlib",
  seaborn: "Seaborn",
  llm: "LLM",
  "large language model": "LLM",
  "large language models": "LLM",
  rag: "RAG",
  "generative ai": "Generative AI",
  genai: "Generative AI",
  chatbot: "Chatbot",
  langchain: "LangChain",
  "hugging face": "Hugging Face",
  huggingface: "Hugging Face",
  transformers: "Transformers",
  openai: "OpenAI",
  "statistical modeling": "Statistical Modeling",
  "statistical analysis": "Statistical Analysis",
  "a/b testing": "A/B Testing",
  abtesting: "A/B Testing",

  // --- SDE / CS ---
  sde: "SDE",
  "software engineer": "SDE",
  "software engineering": "SDE",
  "software development": "SDE",
  swe: "SDE",
  "full stack": "Full Stack",
  fullstack: "Full Stack",
  frontend: "Frontend",
  "front end": "Frontend",
  backend: "Backend",
  "back end": "Backend",
  devops: "DevOps",
  "data structures": "Data Structures",
  algorithms: "Algorithms",
  dsa: "DSA",
  "computer science": "Computer Science",
  cs: "Computer Science",
  "system design": "System Design",
  "distributed systems": "Distributed Systems",
  oop: "OOP",
  "object oriented": "OOP",
};

export const ALL_SKILLS = Array.from(
  new Set(Object.values(SKILL_ALIASES)),
).sort();

export const CURATED_COMPANIES: {
  name: string;
  slug: string;
  companyType: CompanyType;
  atsType: "greenhouse" | "lever" | "ashby" | null;
  atsBoard: string | null;
  website: string;
  logo: string | null;
}[] = [
  // --- Greenhouse ATS (verified) ---
  {
    name: "Razorpay",
    slug: "razorpay",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "razorpaysoftwareprivatelimited",
    website: "https://razorpay.com/jobs",
    logo: null,
  },
  {
    name: "PhonePe",
    slug: "phonepe",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "phonepe",
    website: "https://www.phonepe.com/careers",
    logo: null,
  },
  {
    name: "Groww",
    slug: "groww",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "groww",
    website: "https://groww.in/careers",
    logo: null,
  },
  {
    name: "Postman",
    slug: "postman",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "postman",
    website: "https://www.postman.com/careers",
    logo: null,
  },
  {
    name: "InMobi",
    slug: "inmobi",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "inmobi",
    website: "https://www.inmobi.com/careers",
    logo: null,
  },
  {
    name: "Stripe",
    slug: "stripe",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "stripe",
    website: "https://stripe.com/jobs",
    logo: null,
  },
  {
    name: "Databricks",
    slug: "databricks",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "databricks",
    website: "https://www.databricks.com/careers",
    logo: null,
  },
  {
    name: "Atlassian",
    slug: "atlassian",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "atlassian",
    website: "https://www.atlassian.com/company/careers",
    logo: null,
  },
  {
    name: "GitLab",
    slug: "gitlab",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "gitlab",
    website: "https://about.gitlab.com/jobs",
    logo: null,
  },
  {
    name: "Dropbox",
    slug: "dropbox",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "dropbox",
    website: "https://www.dropbox.com/jobs",
    logo: null,
  },
  {
    name: "Unity",
    slug: "unity",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "unity",
    website: "https://careers.unity.com",
    logo: null,
  },
  {
    name: "Vercel",
    slug: "vercel",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "vercel",
    website: "https://vercel.com/careers",
    logo: null,
  },
  {
    name: "Asana",
    slug: "asana",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "asana",
    website: "https://asana.com/jobs",
    logo: null,
  },
  {
    name: "Grammarly",
    slug: "grammarly",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "grammarly",
    website: "https://www.grammarly.com/jobs",
    logo: null,
  },
  {
    name: "Coinbase",
    slug: "coinbase",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "coinbase",
    website: "https://www.coinbase.com/careers",
    logo: null,
  },
  {
    name: "GitHub",
    slug: "github",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "github",
    website: "https://github.com/about/careers",
    logo: null,
  },
  {
    name: "Robinhood",
    slug: "robinhood",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "robinhood",
    website: "https://robinhood.com/us/en/careers",
    logo: null,
  },
  {
    name: "DoorDash",
    slug: "doordash",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "doordash",
    website: "https://careersatdoordash.com",
    logo: null,
  },
  {
    name: "Airbnb",
    slug: "airbnb",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "airbnb",
    website: "https://careers.airbnb.com",
    logo: null,
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "cloudflare",
    website: "https://www.cloudflare.com/careers",
    logo: null,
  },
  {
    name: "Datadog",
    slug: "datadog",
    companyType: "MNC",
    atsType: "greenhouse",
    atsBoard: "datadog",
    website: "https://www.datadoghq.com/careers",
    logo: null,
  },
  {
    name: "Anthropic",
    slug: "anthropic",
    companyType: "STARTUP",
    atsType: "greenhouse",
    atsBoard: "anthropic",
    website: "https://www.anthropic.com/careers",
    logo: null,
  },
  // --- Lever ATS (verified, case-sensitive slug) ---
  {
    name: "CRED",
    slug: "cred",
    companyType: "STARTUP",
    atsType: "lever",
    atsBoard: "cred",
    website: "https://cred.club/careers",
    logo: null,
  },
  {
    name: "Meesho",
    slug: "meesho",
    companyType: "STARTUP",
    atsType: "lever",
    atsBoard: "meesho",
    website: "https://www.meesho.com/careers",
    logo: null,
  },
  {
    name: "Sprinto",
    slug: "sprinto",
    companyType: "STARTUP",
    atsType: "lever",
    atsBoard: "Sprinto",
    website: "https://sprinto.com/careers",
    logo: null,
  },
  {
    name: "Palantir",
    slug: "palantir",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "palantir",
    website: "https://www.palantir.com/careers",
    logo: null,
  },
  {
    name: "Plaid",
    slug: "plaid",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "plaid",
    website: "https://plaid.com/careers",
    logo: null,
  },
  {
    name: "Revolut",
    slug: "revolut",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "revolut",
    website: "https://www.revolut.com/careers",
    logo: null,
  },
  {
    name: "Confluent",
    slug: "confluent",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "confluent",
    website: "https://www.confluent.io/careers",
    logo: null,
  },
  {
    name: "Klarna",
    slug: "klarna",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "klarna",
    website: "https://www.klarna.com/careers",
    logo: null,
  },
  {
    name: "1Password",
    slug: "1password",
    companyType: "MNC",
    atsType: "lever",
    atsBoard: "1password",
    website: "https://1password.com/jobs",
    logo: null,
  },
  // --- Ashby ATS (verified) ---
  {
    name: "Sarvam AI",
    slug: "sarvam-ai",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "sarvam",
    website: "https://www.sarvam.ai/careers",
    logo: null,
  },
  {
    name: "Rippling",
    slug: "rippling",
    companyType: "MNC",
    atsType: "ashby",
    atsBoard: "rippling",
    website: "https://www.rippling.com/careers",
    logo: null,
  },
  {
    name: "Notion",
    slug: "notion",
    companyType: "MNC",
    atsType: "ashby",
    atsBoard: "notion",
    website: "https://www.notion.so/careers",
    logo: null,
  },
  {
    name: "Loom",
    slug: "loom",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "loom",
    website: "https://www.loom.com/careers",
    logo: null,
  },
  {
    name: "Snowflake",
    slug: "snowflake",
    companyType: "MNC",
    atsType: "ashby",
    atsBoard: "snowflake",
    website: "https://www.snowflake.com/careers",
    logo: null,
  },
  {
    name: "Figma",
    slug: "figma",
    companyType: "MNC",
    atsType: "ashby",
    atsBoard: "figma",
    website: "https://www.figma.com/careers",
    logo: null,
  },
  {
    name: "Linear",
    slug: "linear",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "linear",
    website: "https://linear.app/careers",
    logo: null,
  },
  {
    name: "Cursor",
    slug: "cursor",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "cursor",
    website: "https://cursor.sh/careers",
    logo: null,
  },
  {
    name: "Perplexity",
    slug: "perplexity",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "perplexity",
    website: "https://perplexity.ai/careers",
    logo: null,
  },
  {
    name: "Cohere",
    slug: "cohere",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "cohere",
    website: "https://cohere.com/careers",
    logo: null,
  },
  {
    name: "Amplitude",
    slug: "amplitude",
    companyType: "MNC",
    atsType: "ashby",
    atsBoard: "amplitude",
    website: "https://amplitude.com/careers",
    logo: null,
  },
  {
    name: "Vanta",
    slug: "vanta",
    companyType: "STARTUP",
    atsType: "ashby",
    atsBoard: "vanta",
    website: "https://vanta.com/careers",
    logo: null,
  },
  // --- Companies with unsupported ATS (listed for discovery, non-ATS sources may cover them) ---
  {
    name: "Swiggy",
    slug: "swiggy",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://careers.swiggy.com",
    logo: null,
  },
  {
    name: "Zomato",
    slug: "zomato",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.zomato.com/careers",
    logo: null,
  },
  {
    name: "Zepto",
    slug: "zepto",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.zeptonow.com/careers",
    logo: null,
  },
  {
    name: "Rapido",
    slug: "rapido",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.rapido.bike/careers",
    logo: null,
  },
  {
    name: "Ola",
    slug: "ola",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.olacabs.com/careers",
    logo: null,
  },
  {
    name: "Google",
    slug: "google",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://careers.google.com",
    logo: null,
  },
  {
    name: "Microsoft",
    slug: "microsoft",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://careers.microsoft.com",
    logo: null,
  },
  {
    name: "Amazon",
    slug: "amazon",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.amazon.jobs",
    logo: null,
  },
  {
    name: "Canva",
    slug: "canva",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.canva.com/careers",
    logo: null,
  },
  {
    name: "Flipkart",
    slug: "flipkart",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.flipkart.com/careers",
    logo: null,
  },
  {
    name: "Goldman Sachs",
    slug: "goldman-sachs",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.goldmansachs.com/careers",
    logo: null,
  },
  {
    name: "Adobe",
    slug: "adobe",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.adobe.com/careers",
    logo: null,
  },
  {
    name: "Salesforce",
    slug: "salesforce",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.salesforce.com/company/careers",
    logo: null,
  },
  {
    name: "Uber",
    slug: "uber",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.uber.com/us/en/careers",
    logo: null,
  },
  {
    name: "Cisco",
    slug: "cisco",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://jobs.cisco.com",
    logo: null,
  },
  {
    name: "IBM",
    slug: "ibm",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.ibm.com/careers",
    logo: null,
  },
  {
    name: "Oracle",
    slug: "oracle",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.oracle.com/careers",
    logo: null,
  },
  {
    name: "Accenture",
    slug: "accenture",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.accenture.com/in-en/careers",
    logo: null,
  },
  {
    name: "Infosys",
    slug: "infosys",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.infosys.com/careers",
    logo: null,
  },
  {
    name: "TCS",
    slug: "tcs",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.tcs.com/careers",
    logo: null,
  },
  {
    name: "Walmart",
    slug: "walmart",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://careers.walmart.com",
    logo: null,
  },
  {
    name: "Meta",
    slug: "meta",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.metacareers.com",
    logo: null,
  },
  {
    name: "Apple",
    slug: "apple",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://jobs.apple.com",
    logo: null,
  },
  {
    name: "Netflix",
    slug: "netflix",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://jobs.netflix.com",
    logo: null,
  },
  {
    name: "Nvidia",
    slug: "nvidia",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.nvidia.com/careers",
    logo: null,
  },
  {
    name: "Pinterest",
    slug: "pinterest",
    companyType: "MNC",
    atsType: null,
    atsBoard: null,
    website: "https://www.pinterestcareers.com",
    logo: null,
  },
  {
    name: "Nykaa",
    slug: "nykaa",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.nykaa.com/careers",
    logo: null,
  },
  {
    name: "Lenskart",
    slug: "lenskart",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://www.lenskart.com/careers",
    logo: null,
  },
  {
    name: "Urban Company",
    slug: "urban-company",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://careers.urbancompany.com",
    logo: null,
  },
  {
    name: "ShareChat",
    slug: "sharechat",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://sharechat.com/careers",
    logo: null,
  },
  {
    name: "Zerodha",
    slug: "zerodha",
    companyType: "STARTUP",
    atsType: null,
    atsBoard: null,
    website: "https://zerodha.com/careers",
    logo: null,
  },
];

export const PAGE_SIZE_DEFAULT = 20;
